name: Deploy to Ubuntu server

# Workflow ishga tushishi uchun manba
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          export SUDO_PASSWORD=${{ secrets.SERVER_PASSWORD }}
          cd /srv/kutubxona_project/kutubxona-frontend
          echo $SUDO_PASSWORD | sudo -S git pull
          echo $SUDO_PASSWORD | sudo -S ./build.sh
